# Generated by Django 4.2.15 on 2024-08-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathproblem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
