# Generated by Django 4.2.15 on 2024-10-10 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maths', '0003_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='math_problem',
            field=models.CharField(default='basic', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizscore',
            name='student',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
