# Generated by Django 4.2.15 on 2024-10-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
